# Generated by Django 4.1.5 on 2023-01-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='added_to_cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(related_name='cart', to='products.product'),
        ),
    ]
